#!/usr/bin/env python3
# PYTHON_ARGCOMPLETE_OK
#
# SPDX-License-Identifier: GPL-2.0-only
#
# Author: Qais Yousef <qyousef@layalina.io>

import argparse
import configparser
import pyjen.plugins.folderjob as FolderJob
import pyjen.jenkins as jenkins
import os
import stat
import re
import time
import json
import fcntl
import requests
import pydoc
import readline

# Helpful to debug connection issues
#import logging
#logging.basicConfig(level=logging.DEBUG)

# Allow tab completion when giving input
readline.set_completer_delims(' \t\n=')
readline.parse_and_bind("tab:complete")

try:
    import argcomplete
except:
    pass

from threading import Thread


#
# Config info
#
CONFIG_PATH=os.path.expanduser('~/.myci')
CONFIG_FILE=os.path.join(CONFIG_PATH, 'config')

TAGS_DB=os.path.join(CONFIG_PATH, 'tagsdb')
TESTS_DB=os.path.join(CONFIG_PATH, 'testsdb')
BUILDS_DB=os.path.join(CONFIG_PATH, 'buildsdb')

DOWNLOAD_LINK=''
VERSION_LINK=''

LOCK_FILE=os.path.join(CONFIG_PATH, 'lock')

if not os.path.exists(CONFIG_PATH):
    os.makedirs(CONFIG_PATH)


#
# Defaults
#
DEFAULT_VIEW='all'


#
# Internal logging
#
LOG_FILE=os.path.join(CONFIG_PATH, 'log')
def LOG(info):
    with open(LOG_FILE, 'a') as f:
        f.write("[" + str(time.time()) + "]: " + info + "\n")


###############################################
#
# Version class manages the version of the
# script and updating to latest version if:
#
#   * Force update if Major is different
#   * Warn to update if Minor is different
#
###############################################
class Version:
    def __init__(self, silent=False):
        self.major = 0
        self.minor = 4
        self.rc = '-beta'

        self.version = '{}.{}{}'.format(self.major, self.minor, self.rc)

        if not silent:
            self.print_version()
        #self.check_new_version()

    def print_version(self):
        print("myci v{}".format(self.version))

    def print_update_msg(self, major, minor):
        print()
        print("############################################")
        print(" A new version is available v{}.{}".format(major, minor))
        print(" Run `myci --update` to update")
        print("############################################")
        print()

    def check_new_version(self):
        r = requests.get(VERSION_LINK)
        r = r.json()
        major = r['Major']
        minor = r['Minor']

        if self.major < major:
            self.print_update_msg(major, minor)
            raise Exception("Must update to the latest version!")

        if self.minor < minor:
            self.print_update_msg(major, minor)

    def create_version_json(self):
        with open("version", 'w') as fp:
            version = {}
            version['Major'] = self.major
            version['Minor'] = self.minor

            json.dump(version, fp)

    def update(self):
        p = os.path.abspath(__file__)
        r = requests.get(DOWNLOAD_LINK)
        with open(p, 'w') as fp:
            fp.write(r.text)


###############################################
#
# Config class manages user configuration file
#
###############################################
class Config:
    # Public functions
    def get_url(self):
        return self.config.get('jenkins', 'url')

    def get_view(self):
        return self.config.get('jenkins', 'view')

    def get_ssl_ca(self):
        return self.config.get('jenkins', 'ssl_ca')

    def get_username(self):
        return self.config.get('user', 'username')

    def get_token(self):
        return self.config.get('user', 'token')

    def get_email(self):
        return self.config.get('user', 'email')

    def get_url_length(self):
        return self.config.get('settings', 'url_length')

    # Private functions
    def read_username(self):
        print('Jenkins username: ')
        username = input()
        self.config.set('user', 'username', username)

    def read_token(self):
        print('Jenkins token: ')
        token = input()
        self.config.set('user', 'token', token)

    def read_email(self):
        print('Email: ')
        token = input()
        self.config.set('user', 'email', token)

    def read_url(self):
        print('Jenkins url: ')
        url = input()

        if url:
            self.config.set('jenkins', 'url', url)

    def read_ssl_ca(self):
        found = False

        while not found:
            print('Jenkins ssl certificate: ')
            ssl_ca = input()
            ssl_ca = os.path.expanduser(ssl_ca)
            ssl_ca = os.path.abspath(ssl_ca)

            if os.path.exists(ssl_ca):
                self.config.set('jenkins', 'ssl_ca', ssl_ca)
                found = True
            else:
                print("{} doesn't exist.".format(ssl_ca))

    # Initialize everything
    def __init__(self):
        self.config = configparser.ConfigParser()

        if os.path.isfile(CONFIG_FILE):
            self.config.read(CONFIG_FILE)

        if not self.config.has_section('user'):
            self.config.add_section('user')
            print('No user configuration found')
            self.read_username()
            self.read_token()
            self.read_email()
        else:
            if not self.config.has_option('user', 'username'):
                print('Missing jenkins username')
                self.read_username()
            if not self.config.has_option('user', 'token'):
                print('Missing jenkins token')
                self.read_token()
            if not self.config.has_option('user', 'email'):
                print('Missing jenkins email')
                self.read_email()

        if not self.config.has_section('jenkins'):
            self.config.add_section('jenkins')
            print('No jenkins configuration found')
            self.read_url()
            self.read_ssl_ca()
            self.config.set('jenkins', 'view', DEFAULT_VIEW)
        else:
            if not self.config.has_option('jenkins', 'url'):
                print('Missing jenkins url')
                self.read_url()
            if not self.config.has_option('jenkins', 'ssl_ca'):
                print('Missing jenkins ssl certificate')
                self.read_ssl_ca()
            if not self.config.has_option('jenkins', 'view'):
                self.config.set('jenkins', 'view', DEFAULT_VIEW)

        if not self.config.has_section('settings'):
            self.config.add_section('settings')
            self.config.set('settings', 'url_length', '{}'.format(50))

        with open(CONFIG_FILE, 'w') as config_file:
            self.config.write(config_file)

        # Since we store the password in plaintext, protect it so that only
        # the owner can read it
        os.chmod(CONFIG_FILE, stat.S_IRUSR | stat.S_IWUSR)


###############################################
#
# TestsDB manages talking to the tests database
#
# The DB is a simple json file. But we can use
# something more sophisticated if we need later
#
###############################################
class TestsDB:
    def __init__(self):
        # Load the Json file, if not empty
        if os.path.exists(TESTS_DB) and os.path.getsize(TESTS_DB):
            with open(TESTS_DB) as fd:
                self.db = json.load(fd)
        else:
            self.db = {}

    def exists(self, suite):
        if suite in self.db.keys():
            return True

        return False

    def suites(self):
        return self.db.keys()

    def get_tests_list(self, suite):
        if not suite in self.db.keys():
            raise Exception("Test Suite <{}> doesn't exists!".format(suite))

        tests = []
        if isinstance(self.db[suite], list):
            for test in self.db[suite]:
                tests.append(test)
        else:
            tests.append(self.db[suite])

        return tests


###############################################
#
# TagDB manages talking to the tags database
#
# The DB is a simple json file. But we can use
# something more sophisticated if we need later
#
###############################################
class TagsDB:
    def __init__(self):
        # Load the Json file, if not empty
        if os.path.exists(TAGS_DB) and os.path.getsize(TAGS_DB):
            with open(TAGS_DB) as fd:
                self.db = json.load(fd)
        else:
            self.db = {}

    def update_job(self, tag, job, build_number):
        if not self.exists(tag):
            self.db[tag] = {}
            self.db[tag]['jobs'] = {}

        self.db[tag]['jobs'][job] = build_number

        with open(TAGS_DB, 'w') as fd:
            json.dump(self.db, fd, indent=4)

    def update_state(self, tag, finished):
        if not self.exists(tag):
            self.db[tag] = {}

        self.db[tag]['state'] = finished

        with open(TAGS_DB, 'w') as fd:
            json.dump(self.db, fd, indent=4)

    def get_state(self, tag):
        if not self.exists(tag):
            raise Exception("Tag <{}> doesn't exists!".format(tag))

        return self.db[tag]['state']

    def exists(self, tag):
        if tag in self.db.keys():
            return True

        return False

    def get_tags_list(self):
        #
        # Return a copy because when deleting the list will be modified while
        # we're still traversing it.
        #
        return [key for key in self.db.keys()]

    def get_jobs_list(self, tag):
        if not self.exists(tag):
            raise Exception("Tag <{}> doesn't exists!".format(self.tag))

        return self.db[tag]['jobs'].items()

    def get_builds_list(self):
        jobs = []
        for tag in self.get_tags_list():
            for (job, buildnumber) in self.db[tag]['jobs'].items():
                jobs.append("{}:{}".format(job, buildnumber))
        return jobs

    def delete_tag(self, tag):
        if not self.exists(tag):
            raise Exception("Tag <{}> doesn't exists!".format(self.tag))

        del self.db[tag]

        with open(TAGS_DB, 'w') as fd:
            json.dump(self.db, fd, indent=4)


###############################################
#
# BuildsDB manages talking to the builds/jobs
# database
#
# The DB is a simple json file. But we can use
# something more sophisticated if we need later
#
###############################################
class BuildsDB:
    def __init__(self):
        # Load the Json file, if not empty
        if os.path.exists(BUILDS_DB) and os.path.getsize(BUILDS_DB):
            with open(BUILDS_DB) as fd:
                self.db = json.load(fd)
        else:
            self.db = {}
            self.db['jobs'] = []
            self.regenerate()

    def regenerate(self, timeout=60):
        ts1 = self.db['timestamp']
        ts2 = time.time()
        if ts2 - ts1 < timeout:
            return

        self.db['timestamp'] = time.time()
        with open(BUILDS_DB, 'w') as fd:
            json.dump(self.db, fd, indent=4)

        LOG("Regenerate, forking")
        pid = os.fork()
        if pid:
            LOG("Regenerate, parent returned")
            return

        LOG("Regenerate, child start")
        myci = MyCI(silent=True)

        for name in myci.list_jobs():
            # Is it a new job that we didn't see before?
            if name not in self.db['jobs']:
                self.db['jobs'].append(name)
                self.db[name] = []
                lastbuild = 0
            else:
                lastbuild = len(self.db[name])

            job = myci.find_job(name)

            try:
                numbuilds = len(job.all_builds)
                if lastbuild == numbuilds:
                    continue
            except:
                continue

            newbuilds = numbuilds - lastbuild
            for build in job.all_builds[:newbuilds]:
                d = {
                        'url' : build.url,
                        'result' : build.result if build.result else 'Running',
                        'builds' : "{}:{}".format(name, build.number)
                }
                self.db[name].append(d)

        with open(BUILDS_DB, 'w') as fd:
            json.dump(self.db, fd, indent=4)

        LOG("Regenerate, child finished")
        exit(0)

    def get_jobs_list(self):
        return self.db['jobs']

    def get_builds_list(self, job):
        jobs = []
        for build in self.db[job]:
            jobs.append(build['builds'])
        return jobs


###############################################
#
# MyCI class implements the
# different options the user passes to us.
#
# And handles setting up connection with jenkins
#
###############################################
class MyCI:
    def __init__(self, tag=None, param=None, silent=False):
        self.tracked_jobs = []
        self.tag = tag
        self.param = param
        self.silent = silent

        self.version = Version(silent=silent)
        self.config = Config()
        self.tagsdb = TagsDB()
        self.testsdb = TestsDB()
        self.verify_tag()
        self.connect()

    def version_json(self):
        self.version.create_version_json()

    def update(self):
        self.version.update()

    def parse_tag(self):
        s = self.tag

        # Remove all non-word characters (everything except numbers and letters)
        s = re.sub(r"[^\w\s]", '', s)

        # Replace all runs of whitespace with a single dash
        s = re.sub(r"\s+", '_', s)

        self.tag = s

    def verify_tag(self):
        if self.tag is None:
            return

        if self.tagsdb.exists(self.tag):
            raise Exception('Tag <{}> already exists. Clear the tags or choose another name'.format(self.tag))

    def store_tag_job_info(self, job, build_number):
        self.tagsdb.update_job(self.tag, job, build_number)

    def store_tag_finished(self, finished, tag=None):
        if tag is None:
            tag = self.tag

        self.tagsdb.update_state(tag, str(finished))

    def list_tags(self):
        tags = self.tagsdb.get_tags_list()
        for tag in tags:
            print('\t', tag)

    def clear_tags(self):
        # Update the finished status first
        self.status(quite=True)

        tags = self.tagsdb.get_tags_list()
        for tag in tags:
            finished = self.tagsdb.get_state(tag)

            if finished == "True":
                print('\t', 'Deleting', tag)
                self.tagsdb.delete_tag(tag)

    def print_build_info(self, url, result, name, build_number):
        conf_url_len = int(self.config.get_url_length())
        url_len = len(url)
        if url_len > conf_url_len:
            url=url[url_len-conf_url_len:]
        print('\t\t', '{url:<{length}s}'.format(url=url, length=conf_url_len),
              '\t', result if result else 'Running', '\t', '{}:{}'.format(name, build_number))

    def status(self, quite=False):
        tags = self.tagsdb.get_tags_list()
        for tag in sorted(tags):
            is_building = False

            if not quite:
                print('\t', tag)

            for (name, build_number) in self.tagsdb.get_jobs_list(tag):
                job = self.find_job(name)
                build = job.get_build_by_number(build_number)

                if not build:
                    print("Can't find", name, ':', build_number)
                else:
                    is_building = build.is_building or is_building

                    if not quite:
                        self.print_build_info(build.url, build.result, name, build_number)

            self.store_tag_finished(not is_building, tag)
            if not quite:
                print()

    def abort_tag(self, tag):
        print('\t', 'Aborting <{}>'.format(tag))

        for (name, build_number) in self.tagsdb.get_jobs_list(tag):
            job = self.find_job(name)
            build = job.get_build_by_number(build_number)

            if build:
                if build.is_building:
                    print('\t\t', 'Aborting <{}>'.format(name))
                    build.abort()
            else:
                print('\t\t', "Can't find {}({})".format(name, build_number))

    def find_job(self, test_job):
        # Handle hierarchal jobs (jobs inside folders)
        s = test_job.split('/')
        __server = self.server
        job = None

        for test_job in s:
            job = __server.find_job(test_job)
            __server = job

        return job

    def connect(self):
        jenkins_url = self.config.get_url()
        username = self.config.get_username()
        token = self.config.get_token()

        # Set REQUESTS_CA_BUNDLE to allow https connection to the server
        os.environ["REQUESTS_CA_BUNDLE"] = self.config.get_ssl_ca()

        self.server = jenkins.Jenkins(jenkins_url, (username, token))
        if not self.silent:
            print('Connected to ', jenkins_url, self.server.version)
            print()

    def __list_jobs(self, job, path=None):
        if path is None:
            path = job.name

        jobs = []
        try:
            for job in job.jobs:
                jobs.extend(self.__list_jobs(job, path=path + '/' + job.name))
        except:
            pass

        return [path] if not jobs else jobs

    def list_jobs(self):
        view = self.config.get_view()
        view = self.server.find_view(view)
        jobs = []
        for job in view.jobs:
            jobs.extend(self.__list_jobs(job))
        return jobs

    def print_jobs(self):
        view = self.config.get_view()
        print('List of available jobs:')
        for job in self.list_jobs():
            print('\t', job)
        print()

    def print_console(self, test_job, build_number):
        job = self.find_job(test_job)

        if (job):
            build = job.get_build_by_number(build_number)

            if build:
                pydoc.pipepager(build.console_output, cmd='less -R')
                return

        raise Exception("Can't find {}({})".format(test_job, build_number))

    def set_description(self, test_job, build_number, description):
        job = self.find_job(test_job)

        if (job):
            build = job.get_build_by_number(build_number)

            if build:
                build.description = description
                return

        raise Exception("Can't find {}({})".format(test_job, build_number))

    def list_artifacts(self, test_job, build_number):
        job = self.find_job(test_job)
        if (job):
            build = job.get_build_by_number(build_number)

            if build:
                urls = build.artifact_urls
                if not urls:
                    print('No artifacts for {}:{}'.format(test_job, build_number))
                    return

                for url in urls:
                    print(url)
                return

        raise Exception("Can't find {}({})".format(test_job, build_number))

    def get_artifacts(self, test_job, build_number):
        path = '{}:{}-artifacts'.format(test_job, build_number)
        if os.path.exists(path):
            raise Exception('{} already exists'.format(path))

        job = self.find_job(test_job)
        if (job):
            build = job.get_build_by_number(build_number)

            if build:
                urls = build.artifact_urls
                if not urls:
                    print('No artifacts for {}:{}'.format(test_job, build_number))
                    return

                os.makedirs(path)
                for url in urls:
                    artifact = os.path.join(path, os.path.basename(url))
                    print("Downloading {}...".format(artifact), end='\r')
                    r = requests.get(url, auth=(self.config.get_username(), self.config.get_token()))
                    if r.status_code != 200:
                        print("Downloading {}... FAILED ({})".format(artifact, r.status_code))
                        continue
                    else:
                        print("Downloading {}... SUCCESS".format(artifact))

                    with open(artifact, 'wb') as fp:
                        fp.write(r.content)
                return

        raise Exception("Can't find {}({})".format(test_job, build_number))

    def __list_forever(self):
        url = '{}/api/xml?depth=4&xpath=//job[not(ancestor::primaryView)andnot(ancestor::view)andnot(ancestor::node)]/build[keepLog=%22true%22]/url&wrapper=forever'.format(self.config.get_url())
        r = requests.get(url, auth=(self.config.get_username(), self.config.get_token()))
        import defusedxml.ElementTree as et
        forever = et.fromstring(r.text)
        urls = forever.findall('url')
        return [url.text for url in urls]

    def list_forever(self):
        for url in self.__list_forever():
            job, build_number = os.path.split(os.path.dirname(url))
            job = job.replace(self.config.get_url() + '/', '')
            job = job.replace('job/', '')
            description = ""

            job = self.find_job(job)
            if (job):
                build = job.get_build_by_number(int(build_number))

                if build:
                    description = build.description

            print('{url:<{length}s}'.format(url=url, length=100), '\t', description)
        return

    def keep_forever(self, test_job, build_number):
        job = self.find_job(test_job)
        if (job):
            build = job.get_build_by_number(build_number)

            if build:
                build_url = build.url

                if build_url in self.__list_forever():
                    print("{}:{} is already set as keep forever".format(test_job, build_number))
                    return

                url = os.path.join(build_url, 'toggleLogKeep')
                r = requests.post(url, auth=(self.config.get_username(), self.config.get_token()))
                if r.status_code != 200:
                    print("Keep forever {}:{}... FAILED ({})".format(test_job, build_number, r.status_code))
                else:
                    print("Keep forever {}:{}... SUCCESS".format(test_job, build_number))
                return

        raise Exception("Can't find {}({})".format(test_job, build_number))

    def remove_forever(self, test_job, build_number):
        job = self.find_job(test_job)
        if (job):
            build = job.get_build_by_number(build_number)

            if build:
                build_url = build.url

                if build_url not in self.__list_forever():
                    print("{}:{} is not set as keep forever".format(test_job, build_number))
                    return

                url = os.path.join(build_url, 'toggleLogKeep')
                r = requests.post(url, auth=(self.config.get_username(), self.config.get_token()))
                if r.status_code != 200:
                    print("Remove forever {}:{}... FAILED ({})".format(test_job, build_number, r.status_code))
                else:
                    print("Remove forever {}:{}... SUCCESS".format(test_job, build_number))
                return

        raise Exception("Can't find {}({})".format(test_job, build_number))

    def list_builds(self, test_job):
        job = self.find_job(test_job)

        if (job):
            builds = job.all_builds
            limit = 20

            if builds:
                for index, build in enumerate(builds):
                    if index == limit:
                        break
                    self.print_build_info(build.url, build.result, test_job, build.number)

            return

        raise Exception("Can't find {}".format(test_job))

    # Store the required info to track the started tests
    def test_track_jobs(self, job, q):
        self.tracked_jobs.append([job, q])

    # Wait to ensure that we have build numbers for all started jobs
    def __test_wait_tracked_jobs(self):
        print('Collecting tag tracking info...')

        while True:
            for item in self.tracked_jobs:

                job = item[0]
                q = item[1]

                if q.waiting:
                    print(job, ':', q.reason)
                    continue

                if not q.is_valid:
                    print('WARNING: Failed to get build number of: ', job)
                    self.tracked_jobs.remove(item)
                    continue

                try:
                    build_number = q.build.number
                except:
                    print(job, ':', q.reason)
                    continue

                if q.build is None:
                    print('WARNING: Failed to get build number of: ', job)
                    self.tracked_jobs.remove(item)
                    continue

                self.store_tag_job_info(job, build_number)

                self.tracked_jobs.remove(item)

            if len(self.tracked_jobs):
                time.sleep(10)
            else:
                break

    def test_wait_tracked_jobs(self):
        wait = Thread(target=self.__test_wait_tracked_jobs)
        wait.setDaemon(True)
        wait.start()

        # Wait until done
        #
        # User can interrupt, but after prompted to confirm first.
        while wait.is_alive():
            try:
                wait.join()
                break
            except:
                try:
                    print("WARNING: Terminating now means partial jobs would be tracked only. Jenkins will still run these jobs.")
                    print("Terminate(Y/y)?: ", end='')
                    done = input()
                    if done.lower() == 'y':
                        break
                except:
                    continue

    def __test_job(self, test_job, extra_params={}):
        job = self.find_job(test_job)

        if not self.tag:
            self.parse_tag()

        if self.param:
            for param in self.param:
                (p, v) = param.split('=', 1)
                extra_params[p] = v

        if job:
            print('[Building] ', job.name)
            q = job.start_build(**extra_params)
            self.test_track_jobs(test_job, q)
        else:
            raise Exception("Can't find <{}>".format(test_job))

    def test_job(self, test_job):
        try:
            self.__test_job(test_job)
        finally:
            self.test_wait_tracked_jobs()

    def test_list(self, jobs_list):
        for test_job in jobs_list:

            params = {}
            try:
                for param in test_job['params']:
                    (p, v) = param.split('=', 1)
                    params[p] = v
            except:
                pass

            self.__test_job(test_job['name'], params)

    def do_test(self, suite):
        try:
            print('Running [', suite, '] test suite..')
            tests = self.testsdb.get_tests_list(suite)
            tests = [tests] if isinstance(tests, str) else tests
            self.test_list(tests)
        finally:
            self.test_wait_tracked_jobs()


###############################################
#
# App class handle user command line options
# and executes what they asked us to do.
#
###############################################
class App:
    def parse_cmdline(self):
        tagsdb = TagsDB()
        testsdb = TestsDB()
        parser = argparse.ArgumentParser(description='''
        MyCI CommandLine Client

        Automatically kick off a test suite of a set of jobs on Jenkins.

        You can define any custom test suites for your project in ~/.myci/testsdb.

        Usage:

            # Run jhealthcheck suite as defined in ~/.myci/testsdb
            myci -S jhealthcheck -t hello-world

            # Run run Jenkins-Healthcheck job
            myci -T "Jenkins-Healthcheck" -t quick-run

            # Show status of kicked jobs
            myci -s

            Will print the status of the all the tags.
        ''', formatter_class=argparse.RawTextHelpFormatter)

        def list_suites(**kwargs):
            return testsdb.suites()

        def list_tags(**kwargs):
            return tagsdb.get_tags_list()

        def list_jobs(**kwargs):
            LOG("argcomplte: list jobs")
            return BuildsDB().get_jobs_list()

        def builds_list(prefix, **kwargs):
            LOG("argcomplte: list builds")
            buildsdb = BuildsDB()
            jobs = buildsdb.get_jobs_list()
            job = prefix.split(':')[0]

            if job in jobs:
                return buildsdb.get_builds_list(job)
            else:
                return [job + ':' for job in jobs]

        parser.add_argument('-S', '--suite', type=str,
                        help='The name of the test suite to run as defined in {}/testsdb'.format(CONFIG_PATH)).completer = list_suites
        parser.add_argument('-t', '--tag', type=str,
                        help='The tag to use to identify the test results. Default uses suite|job-date')
        parser.add_argument('-a', '--abort-tag', type=str,
                        help='Abort all tests started for the specified ABORT_TAG.').completer = list_tags
        parser.add_argument('-T', '--test', type=str,
                        help='Run this single test only. Use -p option to get a list of tests.').completer = list_jobs
        parser.add_argument('--console', type=str,
                        help='Print out the console output of <job:build_number>.').completer = builds_list
        parser.add_argument('--set-description', type=str,
                        help='Set the description of <job:build_number>.').completer = builds_list
        parser.add_argument('--list-artifacts', type=str,
                        help='List artifacts from <job:build_number>.').completer = builds_list
        parser.add_argument('--get-artifacts', type=str,
                        help='Download artifacts from <job:build_number>.').completer = builds_list
        parser.add_argument('--list-forever', action='store_true',
                        help='List all keep forever builds.')
        parser.add_argument('--keep-forever', type=str,
                        help='Set <job:build_number> as keep forever.').completer = builds_list
        parser.add_argument('--remove-forever', type=str,
                        help='Unset <job:build_number> as keep forever.').completer = builds_list
        parser.add_argument('-b', '--builds', type=str,
                        help='Print out the status of the last 20 builds of a job.').completer = list_jobs
        parser.add_argument('-P', '--param', type=str, nargs='+', metavar='PARAM=VAL',
                        help='Pass extra parameters to the build job.')
        parser.add_argument('--version-json', action='store_true',
                        help='Create a JSON file containg version info named version in CWD')
        parser.add_argument('--update', action='store_true',
                        help='Update to the latest version and exit')

        group = parser.add_mutually_exclusive_group()
        group.add_argument('-l', '--list-tags', action='store_true',
                        help='Print the list of tags that were tested.')
        group.add_argument('-c', '--clear-tags', action='store_true',
                        help='Remove the tags that were completed.')
        group.add_argument('-s', '--status', action='store_true',
                        help='Print the status of all the tags.')
        group.add_argument('-p', '--print-jobs', action='store_true',
                        help='Print list of available jobs in the view and exit')

        try:
            argcomplete.autocomplete(parser)
        except:
            pass

        self.args = parser.parse_args()

    def run(self):
        #
        # Setup
        #
        self.parse_cmdline()

        # Create a tag if none is passed
        if self.args.tag is None:
            if self.args.suite or self.args.test:
                self.args.tag = self.args.suite if self.args.suite else self.args.test
                self.args.tag += '-' + time.strftime('%Y%m%d-%H%M%S')

        self.myci = MyCI(self.args.tag, self.args.param)

        def parse_build_tuple(build):
            build = build.split(':')
            job = build[0]
            build_number = int(build[1])
            return (job, build_number)

        BuildsDB().regenerate()

        #
        # Now, what did the user ask us to do?
        #
        if self.args.abort_tag:
            self.myci.abort_tag(self.args.abort_tag)
            exit()

        if self.args.console:
            (job, build_number) = parse_build_tuple(self.args.console)
            self.myci.print_console(job, build_number)
            exit()

        if self.args.set_description:
            (job, build_number) = parse_build_tuple(self.args.set_description)
            description = input('Enter descriptin for {}:{}: '.format(job, build_number))
            self.myci.set_description(job, build_number, description)
            exit()

        if self.args.list_artifacts:
            (job, build_number) = parse_build_tuple(self.args.list_artifacts)
            self.myci.list_artifacts(job, build_number)
            exit()

        if self.args.get_artifacts:
            (job, build_number) = parse_build_tuple(self.args.get_artifacts)
            self.myci.get_artifacts(job, build_number)
            exit()

        if self.args.list_forever:
            self.myci.list_forever()
            exit()

        if self.args.keep_forever:
            (job, build_number) = parse_build_tuple(self.args.keep_forever)
            self.myci.keep_forever(job, build_number)
            exit()

        if self.args.remove_forever:
            (job, build_number) = parse_build_tuple(self.args.remove_forever)
            self.myci.remove_forever(job, build_number)
            exit()

        if self.args.builds:
            self.myci.list_builds(self.args.builds)
            exit()

        if self.args.list_tags:
            self.myci.list_tags()
            exit()

        if self.args.clear_tags:
            self.myci.clear_tags()
            exit()

        if self.args.status:
            self.myci.status()
            exit()

        if self.args.print_jobs:
            self.myci.print_jobs()
            exit()

        if self.args.version_json:
            self.myci.version_json()
            exit()

        if self.args.update:
            self.myci.update()
            exit()


        #
        # When triggering 2 tests at the same time, the communication with jenkins
        # seems to get mangled (possibly a bug in pyjen). To avoid the situation
        # altogether, prevent more than a single instance to run at the same time on
        # the same machine.
        #
        fp = open(LOCK_FILE, 'w')
        try:
            fcntl.lockf(fp, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except IOError:
            raise Exception("Another instance is running, trigger one test at a time")


        if self.args.test:
            self.myci.test_job(self.args.test)
            exit()

        #
        # Start the requested tests
        #
        if self.args.suite:
            self.myci.do_test(self.args.suite)
        else:
            for suite in self.testsdb.suites():
                self.myci.do_test(suite)


###############################################
#
#          ## APP START HERE ###
#
###############################################
app = App()
app.run()
